export enum STACK_NAME {
  VUE = "Vue",
  TYPESCRIPT = "Typescript",
  SASS = "Sass",
  NODE = "Node.js",
  POSTGRESQL = "PostgreSQL",
  S3 = "AWS S3",
  EC2 = "AWS EC2",
  FIGMA = "Figma",
  DOCKER = "Docker",
  JENKINS = "Jenkins",
  REACT = "React",
  TENSORFLOW = "Tensorflow",
  KAKAOOAUTH = "Kakao oauth",
  SPRING = "Spring",
  MYSQL = "MySQL",
  REDIS = "Redis",
  PYTHON = "Python",
  DJANGO = "Django",
  FIREBASE = "Firebase",
  VANILLAJS = "VanillaJS",
  OPENAPI = "Open api",
  STYLEDCOMPONENT = "Styled Component",
}
